# Site settings
email: EllaHolmes3@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Ella
description:
url: ""
twitter_username:
default_img: https://unsplash.it/2000/1200?image=1009

# Profile settings
name: Ella Holmes
profile_img: /assets/Ella2LR.jpg
profile:
social:
  github: https://github.com/holme22e
  linkedin: https://www.linkedin.com/in/ella-holmes-0a885070/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
